# Generated by Django 2.2 on 2020-08-23 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
