# Generated by Django 2.2 on 2020-08-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
