# Generated by Django 2.2 on 2020-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200823_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
