# Generated by Django 2.2 on 2020-08-23 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_agenda_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 19, 26, 23, 436844, tzinfo=utc)),
        ),
    ]
